### ISSUE TITLE
Leaking events in new model event publisher

### ISSUE THREAD

**Issue by superchalupa** [looplab/eventhorizon#206] opened 2018-03-28 14:17 UTC
There is no place in sliceeventpublisher that frees events after they are transmitted. What I did to address this is free the list in the EventsToPublish()  call, like so. Not sure if this is your preferred way to do this.
```
diff --git a/vendor/github.com/looplab/eventhorizon/aggregatestore/model/eventpublisher.go b/vendor/github.com/looplab/eventhorizon/aggregatestore/model/eventpublisher.go
index b094041..2447596 100644
--- a/vendor/github.com/looplab/eventhorizon/aggregatestore/model/eventpublisher.go
+++ b/vendor/github.com/looplab/eventhorizon/aggregatestore/model/eventpublisher.go
@@ -36,5 +36,7 @@ func (a *SliceEventPublisher) PublishEvent(e eh.Event) {

 // EventsToPublish implements the EventsToPublish method of the EventPublisher interface.
 func (a *SliceEventPublisher) EventsToPublish() []eh.Event {
-   return *a
+    retval := *a
+    *a = nil
+ return retval
 }
```

**Comment by maxekman** [comment] 2018-03-29 05:14
Should be fixed by #204, did it not?

**Comment by maxekman** [comment] 2018-03-29 06:55
This solution is interesting though, as it minimises the API (to avoid the ClearEvents() method). On the other hand it is a bit magic to change internal state in a getter.

**Comment by maxekman** [comment] 2018-03-29 06:55
@superchalupa Please try the master version and come back with feedback or close this if the issue is indeed fixed.

**Closed** 2018-04-04 00:50 UTC
